### ISSUE TITLE
ModuleNotFoundError: No module named 'click'

### ISSUE THREAD

**Issue by DarekLin** [botofancalin/Esp32_debug_template#3]
Thanks for sharing it. Great tool!
I am trying to run them in the fresh version of  isp-idf 4.2 and when I try to click on e.g pyMenu button I received error:
```
Microsoft Windows [Version 10.0.18363.1379]
(c) 2019 Microsoft Corporation. Wszelkie prawa zastrzeżone.

D:\projects\esp32\idf\Esp32_debug_template>powershell idf.py menuconfig
Traceback (most recent call last):
  File "C:\esp\esp-idf\tools\idf.py", line 45, in <module>
    from idf_py_actions.tools import (executable_exists, idf_version, merge_action_lists, realpath)  # noqa: E402
  File "C:\esp\esp-idf\tools\idf_py_actions\tools.py", line 1, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```
Also, when starting the project, I was not asked about:
..."Note: Allow VSCode to use cmd.exe when asked."...
Could you help to resolve this problem?

**Comment by remibert** [comment]
A very late answer, because I also just had this problem, and I just solved it, for others who will be looking for the solution: the default version of python must be 3.10, if you have 3.11 that made this mistake.

**Comment by ziadelbouriny** [comment]
Does anyone has a solution for this error?
